version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=chat_user
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=chat_database
